/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "ApiService": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "CommentsPostgres": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "CommentsVpc": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "Frontend": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}
